version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 80:8080
    restart: always
    environment:
      - JAVA_OPTS=
        -Djenkins.install.runSetupWizard=false
        -Djava.awt.headless=true
    volumes:
      - jenkins-data:/var/jenkins_home
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

volumes:
  jenkins-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
